# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc26f27035cd522fe7af7fdc3daab683cbfb5597c06df2051eeb32623f08cccafa6a792a8879c9701cd0a450b14e45b6a4340be6ba7647f517f41611373f8c77

test:
  secret_key_base: 6e92f71ea579a13e3a44df0de301844ce60fbbb3e90678c70dbe452e4c663bc6667749d8ad5cecd274fa7091bd93aad9c17a8e992f7bb0a3edc4316e0c6aca38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
